const experiences = [
  {
    company: 'Samvidhan Leadership Program',
    role: 'Data Analyst / Analytics Consultant',
    period: 'Jul 2025 – Nov 2025',
    location: 'India',
    type: 'Previous',
    color: 'border-blue-500',
    dotColor: 'bg-blue-500',
    glowColor: 'shadow-blue-500/30',
    responsibilities: [
      'Designed analytics dashboards and reports to monitor campaign and field performance metrics',
      'Performed large-scale election data analysis to identify constituency-level trends and anomalies',
      'Developed Power BI dashboards to support leadership decision-making and reporting',
      'Built Python-based automation and data extraction workflows for structured analysis',
    ],
    tech: ['Power BI', 'Python', 'SQL', 'Excel'],
  },

  {
    company: 'Shivaji Infotech',
    role: 'Data Analyst',
    period: 'Aug 2024 – Jun 2025',
    location: 'India',
    type: 'Previous',
    color: 'border-cyan-500/50',
    dotColor: 'bg-cyan-500',
    glowColor: 'shadow-cyan-500/20',
    responsibilities: [
      'Served as the sole Data Analyst supporting operations for a U.S. pharmacy client',
      'Developed interactive Power BI dashboards and KPI reports using SQL Server data',
      'Built ETL and data-processing workflows using Python, Pandas and SQL',
      'Automated reporting processes, improving efficiency and reducing manual effort',
      'Designed DAX measures and data models for business reporting and decision-making',
    ],
    tech: ['Power BI', 'SQL Server', 'DAX', 'Python', 'Pandas', 'Excel'],
  },

  {
    company: 'Choudhary Shah & Company',
    role: 'MIS Executive cum Data Analyst',
    period: '2018 – 2024',
    location: 'India',
    type: 'Previous',
    color: 'border-slate-500/50',
    dotColor: 'bg-slate-400',
    glowColor: 'shadow-slate-400/20',
    responsibilities: [
      'Managed financial and operational data used for reporting and business analysis',
      'Prepared periodic MIS reports and dashboards for management',
      'Automated repetitive reporting tasks using Excel formulas, Power Query and VBA',
      'Maintained large datasets and ensured data accuracy and consistency',
      'Supported accounting, taxation and audit-related reporting activities',
    ],
    tech: ['Excel', 'Power Query', 'VBA', 'Power BI', 'MIS Reporting'],
  },

  {
    company: "Vijayan's Fair & Exhibition Pvt. Ltd.",
    role: 'MIS Executive',
    period: '2016 – 2018',
    location: 'India',
    type: 'Previous',
    color: 'border-slate-600/50',
    dotColor: 'bg-slate-500',
    glowColor: 'shadow-slate-500/20',
    responsibilities: [
      'Managed operational reports and maintained event-related data records',
      'Prepared MIS reports to track budgets, registrations and business activities',
      'Supported event operations through reporting and data management',
      'Coordinated with internal teams and stakeholders to ensure smooth execution of exhibitions and trade fairs',
      'Assisted management with data-driven planning and reporting',
    ],
    tech: ['Excel', 'MIS Reporting', 'Data Analysis'],
  },
];